// src/common/constants/enums.js

export const USER_ROLES = {
  SUPER_USER: "SUPER_USER",
  WLS_ADMIN: "WLS_ADMIN",
  USER: "USER",
};

export const ASSESSMENT_STATUSES = {
  PENDING: "PENDING",
  SUBMITTED: "SUBMITTED",
  PARTIAL_SAVED: "PARTIAL_SAVED",
  COMPLETED: "COMPLETED",
};

export const CONCLUSION_STATUSES = {
  PENDING: "PENDING",
  PASSED: "PASSED",
  FAILED: "FAILED",
};

export const WLS_SESSION_STATUSES = {
  NEW: "NEW",
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
  COMPLETED: "COMPLETED",
};

export const QUESTION_TYPES = {
  SINGLE_SELECT: "SINGLE_SELECT",
  MULTI_SELECT: "MULTI_SELECT",
  TRUE_FALSE: "TRUE_FALSE",
  TEXT_INPUT: "TEXT_INPUT",
  SEQUENCE_ORDER: "SEQUENCE_ORDER",
};

// Helpful array for Mongoose enums and validation loops
export const QUESTION_TYPE_VALUES = Object.values(QUESTION_TYPES);
