// src/common/constants/enums.js

export const USER_ROLES = {
  SUPER_USER: 'SUPER_USER',
  WLS_ADMIN: 'WLS_ADMIN',
  USER: 'USER',
};

export const WLS_SESSION_STATUSES = {
  NEW: 'NEW',
  ACTIVE: 'ACTIVE',
  POSTPONED: 'POSTPONED',
  COMPLETED: 'COMPLETED',
  INACTIVE: 'INACTIVE',
  CANCELLED: 'CANCELLED',
};